# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:8.0.27
    container_name: mysql
    volumes:
      - "/c/mnt/mysql/data:/var/lib/mysql"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3306:3306