version: "3"
services:
  nginx:
    image: nginx:1.23.0
    container_name: "nginx"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /c/mnt/nginx/html:/usr/share/nginx/html
      - /c/mnt/nginx/logs:/var/log/nginx
      - /c/mnt/nginx/config.d:/etc/nginx/config.d
      - /c/mnt/nginx/nginx.conf:/etc/nginx/nginx.conf
